# Generated by Django 4.2.2 on 2023-10-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=250)),
                ('products_price', models.IntegerField()),
                ('products_descripton', models.TextField()),
                ('products_location', models.CharField(max_length=250)),
                ('farmers_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_price', models.IntegerField()),
                ('farmer_name', models.CharField(max_length=250)),
            ],
        ),
    ]
