# Generated by Django 4.2.2 on 2023-10-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carts_title', models.CharField(max_length=250)),
                ('carts_image', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('carts_name', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='products_image',
            field=models.ImageField(blank=True, null=True, upload_to='Product'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='Product'),
        ),
    ]
