# Generated by Django 4.2.2 on 2023-10-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_create_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_name', models.CharField(max_length=250)),
                ('sell_image', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('sell_price', models.IntegerField()),
                ('sell_description', models.TextField()),
            ],
        ),
    ]
