# Generated by Django 4.2.2 on 2023-10-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sell'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_user',
            new_name='farmer_user',
        ),
    ]
