# Generated by Django 4.2.2 on 2023-10-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_create_user_farmer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('user_mobileno', models.TextField()),
                ('user_Email', models.TextField()),
                ('user_address', models.TextField()),
                ('user_password', models.CharField(max_length=250)),
            ],
        ),
    ]
