# Generated by Django 4.2.2 on 2023-10-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='carts_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='farmer_user',
            name='user_mobileno',
            field=models.CharField(max_length=250),
        ),
    ]
