# Generated by Django 4.2.2 on 2023-10-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_carts_carts_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_user',
            name='user_Email',
            field=models.CharField(max_length=250),
        ),
    ]
