# Generated by Django 4.2.2 on 2023-10-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_farmer_user_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_user',
            name='user_Email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='customer_user',
            name='user_mobileno',
            field=models.CharField(max_length=250),
        ),
    ]
