# Generated by Django 4.2.2 on 2023-10-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customer_user_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='products_descripton',
            new_name='products_description',
        ),
        migrations.AlterField(
            model_name='products',
            name='products_name',
            field=models.CharField(default='YourDefaultValueHere', max_length=250),
        ),
    ]
