# Generated by Django 4.2.2 on 2023-10-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_products_descripton_products_products_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='sell_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='sell_price',
            field=models.TextField(),
        ),
    ]
