# Generated by Django 4.2.2 on 2023-10-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_sell_sell_name_alter_sell_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='sell_image',
            field=models.ImageField(blank=True, null=True, upload_to='sell'),
        ),
    ]
